### PR TITLE
Fix buffer_options test to assume Rails environment

### PR DESCRIPTION
**Pull request by k0kubun**
Fix test failure caused by https://github.com/haml/haml/commit/c9472d0633d8c93c642876c2100f57a9ab21721a.

@amatsuda WDYT?

### CODE REVIEW

**Comment by k0kubun** [comment]
OMG, it failed... :fearful:

**Comment by k0kubun** [comment]
It's randomly failing... :fearful:

**Comment by amatsuda** [comment]
@k0kubun Just pushed 417a48bb591c2daa213005c081d370dd0a797eb2 to fix the test order dependency problem. Can you please rebase and push -f to see if the tests are 💚 now?

**Comment by k0kubun** [comment]
Tests are :white_check_mark:

**Pull request merged**
