### PR TITLE
Add a gotchas section to Interpolation.

### PR DESCRIPTION
**Pull request by envygeeks**
Adds `%span #{'{'}` to the gotchas section.

### CODE REVIEW

**Comment by envygeeks** [comment]
Ref #832

**Comment by norman** [comment]
This is super passive agressive. Thanks anyway, I'll close this and add the docs myself.

**Comment by envygeeks** [comment]
Passive aggressive? I was pretty direct in my saying that if somebody pointed where I would add the docs so I was being absolutely aggressive and sticking to what I said I would do.

**Comment by norman** [comment]
Ok, thanks.

**Pull request closed without merging**
