### PR TITLE
Replace Haml with Hamlit

### PR DESCRIPTION
**Pull request by k0kubun**
As per https://github.com/haml/haml/pull/1057#issuecomment-855927513, this PR replaces the entire repository except for a few docs with Hamlit, and rename Hamlit to Haml. To reserve git history and copyright of original contributors, this merges all git history of Hamlit.

### CODE REVIEW

**Comment by hcatlin** [comment]
Why close this?

**Comment by k0kubun** [comment]
I commented that at https://github.com/haml/haml/pull/1057#issuecomment-887703265

**Comment by hcatlin** [comment]
@k0kubun I do! I'm more likely to do the beta / hard cut over with the Hamlit branch here than do the other ones.

I'm just finishing up shutting down my company, so only starting to get back into coding.

**Comment by hcatlin** [comment]
This has been effectively "merged" as the new `main` branch for 6.x.x preview development.

**Comment by k0kubun** [comment]
Great, thanks!

**Comment by k0kubun** [comment]
I fixed known third-party Haml integration problems mentioned in https://github.com/haml/haml/pull/1057#issuecomment-856455016httpshttps://github.com/haml/haml/pull/1057#issuecomment-856455016https at #1070 and #1071. We may want to try an alpha release in near future.

**Pull request closed without merging**
